version: '3.8'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=dev
      - DEBUG=True
    volumes:
      - ./backend:/app/backend
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: bash -lc "npm install && npm start"
