# Generated by Django 4.2.24 on 2025-09-30 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='clubs', to='admin_system.student'),
        ),
    ]
