# Generated by Django 4.2.24 on 2025-09-22 18:46

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourcePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('person_type', models.CharField(choices=[('industry_expert', 'Industry Expert'), ('alumnus', 'Alumnus'), ('guest_faculty', 'Guest Faculty'), ('consultant', 'Consultant'), ('entrepreneur', 'Entrepreneur'), ('researcher', 'Researcher')], default='industry_expert', max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=100)),
                ('experience_years', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('expertise_areas', models.TextField()),
                ('bio', models.TextField(blank=True)),
                ('linkedin_profile', models.URLField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('preferred_contact_method', models.CharField(default='email', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_sessions', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('workshop_type', models.CharField(choices=[('technical', 'Technical Workshop'), ('soft_skills', 'Soft Skills'), ('entrepreneurship', 'Entrepreneurship'), ('career_guidance', 'Career Guidance'), ('industry_trends', 'Industry Trends'), ('research', 'Research Methodology')], default='technical', max_length=20)),
                ('target_years', models.CharField(default='1,2,3,4', max_length=50)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=200)),
                ('max_participants', models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(1)])),
                ('registration_deadline', models.DateTimeField()),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('certificate_provided', models.BooleanField(default=True)),
                ('materials_provided', models.BooleanField(default=False)),
                ('prerequisites', models.TextField(blank=True)),
                ('learning_outcomes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('confirmed', 'Confirmed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_workshops', to='admin_system.staff')),
                ('resource_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='resource_person_management.resourceperson')),
                ('target_departments', models.ManyToManyField(blank=True, related_name='workshops', to='admin_system.department')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSharingPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('post_type', models.CharField(choices=[('article', 'Article'), ('tutorial', 'Tutorial'), ('case_study', 'Case Study'), ('industry_update', 'Industry Update'), ('research_paper', 'Research Paper'), ('best_practice', 'Best Practice')], default='article', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('featured_image', models.CharField(blank=True, max_length=500)),
                ('attachments', models.TextField(blank=True)),
                ('target_audience', models.CharField(blank=True, max_length=100)),
                ('difficulty_level', models.CharField(default='intermediate', max_length=20)),
                ('estimated_read_time', models.IntegerField(default=5)),
                ('views_count', models.IntegerField(default=0)),
                ('likes_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='resource_person_management.resourceperson')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_type', models.CharField(choices=[('career_guidance', 'Career Guidance'), ('project_mentoring', 'Project Mentoring'), ('research_guidance', 'Research Guidance'), ('entrepreneurship', 'Entrepreneurship Guidance'), ('technical_help', 'Technical Help')], default='career_guidance', max_length=20)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('preferred_date', models.DateTimeField()),
                ('actual_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15), django.core.validators.MaxValueValidator(180)])),
                ('mode', models.CharField(default='online', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('student_feedback', models.TextField(blank=True)),
                ('resource_person_feedback', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resource_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='resource_person_management.resourceperson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='admin_system.student')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('attendance_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('feedback_rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback_comments', models.TextField(blank=True)),
                ('certificate_issued', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('confirmed', 'Confirmed'), ('attended', 'Attended'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show')], default='registered', max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_registrations', to='admin_system.student')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='resource_person_management.workshop')),
            ],
            options={
                'unique_together': {('workshop', 'student')},
            },
        ),
        migrations.CreateModel(
            name='PostInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('like', 'Like'), ('bookmark', 'Bookmark'), ('share', 'Share')], max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='resource_person_management.knowledgesharingpost')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_interactions', to='admin_system.student')),
            ],
            options={
                'unique_together': {('post', 'student', 'interaction_type')},
            },
        ),
    ]
